name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]   # o la rama que uses

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # SPA fallback (copiamos index.html a 404.html para evitar 404 en refrescos)
      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      # incluir CNAME en dist (si prefieres generarlo en runtime)
      - name: Add CNAME
        run: echo "calculadorainteres.es" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
